### ISSUE TITLE
Code for model training, maintenance status?

### ISSUE THREAD

**Issue by g-simmons** [oaraque/moral-foundations#10]
Hi there, 

Just wondering what the maintenance status for this repo is, and whether code for model training will be released. 

I would like to reproduce the training to obtain model files that are compatible with a recent sklearn version - the original training code would be very helpful for this.

Thanks!

**Comment by oaraque** [comment]
The updated models have been published in commit 19be687, version 0.2.13.

Unfortunately, the original datasets are not public and we do not have rights to disclose them.
