### ISSUE TITLE
API options and paper methods; unigrams + SIMON model

### ISSUE THREAD

**Issue by g-simmons** [oaraque/moral-foundations#11]
Hi there,

I'm wondering if the mapping below is the correct mapping between methods available in this package and the methods in the paper. I'm also wondering whether the unigram+simon model from the paper is available, it doesn't appear in the list of models here: https://github.com/oaraque/moral-foundations/blob/2be815db653ec769587e53eb46557b7bfc87058a/moralstrength/estimators.py#L10-L15

```
N/A                         -->     Baseline: Frequency MFD
unigram                     -->     unigrams
N/A                         -->     SOTA: Lin et al 
count                       -->     Moral Freq 
freq                        -->     Moral Stats 
simon                       -->     SIMON 
simon+count                 -->     SIMON + Moral Freq 
simon+freq                  -->     SIMON + Moral Stats 
simon+count+freq            -->     SIMON + Moral Freq + Moral Stats 
unigram+count               -->     unigrams + Moral Freq 
unigram+freq                -->     unigrams + Moral Stats 
unigram+count+freq          -->     unigrams + Moral Freq + Moral Stats 
????                        -->     unigrams + SIMON                            is this model available?
simon+unigram+count         -->     unigrams + SIMON + Moral Freq                     
simon+unigram+freq          -->     unigrams + SIMON + Moral Stats 
simon+unigram+count+freq    -->     unigrams + SIMON + Moral Freq + Moral Stats 
```

**Comment by oaraque** [comment]
Hello,

Thank you for your interest! Indeed, that mapping is correct. 

You can check all available models [here](https://github.com/oaraque/moral-foundations/tree/master/moralstrength/export). Although they are usable, for most applications it probably makes sense to extract new features and train new models from scratch.
