### ISSUE TITLE
1000 lemmas?

### ISSUE THREAD

**Issue by catmoez** [oaraque/moral-foundations#12]
Hi,

Not a technical issue but I noticed the article mentions having about 1000 words in the lexicon -- I am only finding about 500 from the files posted here?

Looks very interesting, thanks!

Best regards,
Katie

**Comment by oaraque** [comment]
Hello,

Thank you for your interest in our software.

I am not sure to what files you refer, but basically we have two versions of the lexicon. An initial version [here](https://github.com/oaraque/moral-foundations/tree/master/moralstrength/annotations), and an updated version that is [here](https://github.com/oaraque/moral-foundations/tree/master/moralstrength/annotations/v1.1).

I would recommend using the newest version, the default behaviour in the library. Besides, the updated version does indeed have larger vocabulary size than the original.

**Comment by catmoez** [comment]
Thank you, will use the newer one! 

I'm still seeing only 478 words in the version 1 and about 2,800 in the newer version, though. This is fine but was just a bit confused as the article says there are 1,000 total (https://arxiv.org/pdf/1904.08314 p.7).

**Comment by oaraque** [comment]
I am not sure of the correspondence at the moment, I believe the initial version was somehow filtered for the software package. In any case, the second version is by far the recommended.

Thank you again!
