### ISSUE TITLE
pip not sufficient

### ISSUE THREAD

**Issue by rishabhjoshi** [oaraque/moral-foundations#3]
Hi
I installed your package using pip and tried to run a simple code from the readme. It gives me a file not found error : <pythonpath>/site-packages/moralstrength/export/model.pck . 
When I check the moralstrength folder, the export folder is missing. 

If I manually download the export folder from this repo and paste it there, the error changes to a ZeroDivisionError: division by zero error. (probably due to sklearn version mismatch). 

The traceback is as follows : 

> ZeroDivisionError                         Traceback (most recent call last)
> <ipython-input-15-9f3abca3cb08> in <module>
>       1 text = "PLS help #HASHTAG's family. No one prepares for this. They are in need of any assistance you can offer"
> ----> 2 moralstrength.string_moral_values(text)
> 
> /usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/moralstrength/moralstrength.py in string_moral_values(text, model)
>      95     if model not in models:
>      96         raise ValueError('Invalid model "{}" specified. Valid models are: {}'.format(moral,models))
> ---> 97     return {moral: estimate(text=text, moral=moral, model=model)[0] for moral in moral_options_predictions}
>      98 
>      99 # def file_moral_value(filename,trait,model):
> 
> /usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/moralstrength/moralstrength.py in <dictcomp>(.0)
>      95     if model not in models:
>      96         raise ValueError('Invalid model "{}" specified. Valid models are: {}'.format(moral,models))
> ---> 97     return {moral: estimate(text=text, moral=moral, model=model)[0] for moral in moral_options_predictions}
>      98 
>      99 # def file_moral_value(filename,trait,model):
> 
> /usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/moralstrength/estimators.py in estimate(text, moral, model, from_file)
>     100             X.append(X_tmp)
>     101         else:
> --> 102             X_tmp = [form_text_vector(t, model=transformer) for t in text_processed]
>     103             X.append(X_tmp)
>     104     X = np.hstack(X)
> 
> /usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/moralstrength/estimators.py in <listcomp>(.0)
>     100             X.append(X_tmp)
>     101         else:
> --> 102             X_tmp = [form_text_vector(t, model=transformer) for t in text_processed]
>     103             X.append(X_tmp)
>     104     X = np.hstack(X)
> 
> /usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/moralstrength/lexicon_use.py in form_text_vector(text, model)
>      59         return np.concatenate(
>      60             (
> ---> 61                 np.average(v, axis=0),
>      62                 np.std(v, axis=0),
>      63                 np.median(v, axis=0),
> 
> <__array_function__ internals> in average(*args, **kwargs)
> 
> /usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/numpy/lib/function_base.py in average(a, axis, weights, returned)
>     389     if weights is None:
>     390         avg = a.mean(axis)
> --> 391         scl = avg.dtype.type(a.size/avg.size)
>     392     else:
>     393         wgt = np.asanyarray(weights)
> 
> ZeroDivisionError: division by zero

Also, simon models are not present in the export folder provided in the repository. 

Please help. Thanks!

**Comment by oaraque** [comment]
Hi!

Thank you for taking interest in this software.

The problem was a bug in how the moral lexicon was being read. I fixed it, now it should work nicely.

Also, the simon-trained models are not included, since the [simon model](https://www.sciencedirect.com/science/article/pii/S0950705118305926) uses word embeddings, which take a lot of RAM. Thus, we haven't included it. Still, using the other models you can have the same accuracy.

**Comment by oaraque** [comment]
Closing because e6a7ebd fixes it.
